### ISSUE TITLE
Starting the display at a specific address

### ISSUE THREAD

**Issue by quebecsti** [natcl/Artnet#23]
It’s more of a question... feel free to move this if need be.

I’m building some ledstiks, that I ‘d like to have control over addressing..  say stick one, universe 3(that’s easy) address 121-210...  next stick would be 211-300... 

I know I have to offset something in the code.. can’t figure it out

Thanks

**Comment by natcl** [comment]
You will have to re-write a part of the example code:
https://github.com/natcl/Artnet/blob/master/examples/ArtnetNeoPixel/ArtnetNeoPixel.ino
to handle the offset. Are you sending on only one universe ?
