### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by TomislavLepron** [natcl/Artnet#24]
Hello guys, I am new to Arduino world and I am sorry if a ima asking stupid questions. 
The problem i am experiencing with this is that when I open Arduino software on pc and try to include zip library to import software, the "Specified folder/zip file does not contain a valid library " message is displayed. How to get this thing working ? And when I opened unzipped file and opened ArtnetPixelSketch, then when I wanted to compile the file, error occurred saying that Artnet.h wasn't found. Can you help me with this problem and point out what am I doing wrong?

**Comment by nanu-c** [comment]
you have to extract the zip in your sketchbook/library folder
[https://learn.adafruit.com/adafruit-all-about-arduino-libraries-install-use/how-to-install-a-library](url)
