### ISSUE TITLE
Number of LEDs

### ISSUE THREAD

**Issue by mahdibbb** [natcl/Artnet#27]
Hello
Can you run multiple universes with this library and using the Nodemcu(esp8266 12e)? Or more clearly, can I control multiple LEDs?
What depends on the number of LEDs?

**Comment by natcl** [comment]
I never tested this personally over wifi but there is nothing software wise preventing you from adressing multiple universes. I assume limitations will be related to wifi bandwith and CPU speed of the microcontroller. Type of LED used (ws2812 vs APA102) could also influence performance.
