### ISSUE TITLE
Any example with MAX/MSP or Touch Designer ?

### ISSUE THREAD

**Issue by xseignard** [natcl/Artnet#34]
Hello,

I'm looking for examples with MAX/MSP or Touch Designer, sending ArtSync message.

Is there any?

Regards and thanks for your lib!

**Comment by Heljick** [comment]
Hey Xavier ! Giveme a couple of minute I will do one for you running on TD ;) I am from Nantes too btw ^^

**Comment by Heljick** [comment]
[ArtnetSync_TD.zip](https://github.com/natcl/Artnet/files/1927179/ArtnetSync_TD.zip)
Here it is, inside you can found an example for RGB led and one for RGBW led ;) Enjoy !

**Comment by xseignard** [comment]
Hey! That good to see some other "Nantais" here :) Are you still in town? If so we should meet!
Here are the last led stuff I did with my own custom Artnet to led strips controller
https://www.instagram.com/p/Bep1HxNhoiV/
