### ISSUE TITLE
Cannot receive data from lighting console

### ISSUE THREAD

**Issue by roxaskeyheart** [natcl/Artnet#6]
Hi there,

I'm trying to use a lighting console to output Artnet to an Arduino Mega and having some trouble.

I know my console is outputting artnet down the network as I can see the stream coming in on some artnet monitoring software. I also know the library will receive artnet from that same software (as it allows sending basic channel data), but I cannot get the console to register in the library.

For testing purposes I'm using both your Artnet Receive and Artnet Receive Callback examples so I don't think it's a coding issue.

I believe the console is outputting on 2.255.255.255 instead of the standard 255.255.255.255 (which, as it turns out is what the software outputs on).

I have tried setting the arduino IP address to both a 192.x range, 2.x range and 10.x range with no results. Is there anything I can try/edit in the code which you can think of?

**Comment by JustTSK** [comment]
@roxaskeyheart did you solve your issue?
I had the same problem, and it appears that you need to set Subnet Mask: 255.255.255.0 to make Arduino receive broadcasts.
