### ISSUE TITLE
Has no member named 'setBrodcast'

### ISSUE THREAD

**Issue by NorthbySouth** [natcl/Artnet#61]
Im trying to use the ArtnetNeoPixle sketch. Once I go to upload the sketch I receive this error message. 
Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "Arduino Uno"

'using Artnet = class arx::artnet::Manager<EthernetUDP> {aka class arx::artnet::Manager<EthernetUDP>}' has no member named 'setBroadcast'

What can I do to fix this? 
![error artnet](https://user-images.githubusercontent.com/98187370/150593581-cddf0512-2acc-451e-a0ef-470925e4f8d8.JPG)

**Comment by natcl** [comment]
Sounds like you might have an older version of the library, can you check in Artnet.h if setBroadcast is defined ?

**Comment by NorthbySouth** [comment]
I just downloaded the library today from Readme.md section. Where I can download the most up to date version? I will also check Artnet.h right now.

**Comment by NorthbySouth** [comment]
I'm still newer to coding so sorry if this is wrong, but I believe its defined?
![setbrodcast](https://user-images.githubusercontent.com/98187370/150600150-bf582538-d964-43fb-8811-3912c46d46e0.JPG)

**Comment by natcl** [comment]
yes that's strange, do you happen to also have Teensyduino installed ?
There seems to be a conflict of some sort, perhaps 2 versions of the library are installed ?

**Comment by natcl** [comment]
I just re-read your message and it seems like you have a different Artnet library installed than mine,
`using Artnet = class arx::artnet::Manager`
That's not part of this library... Did you install a different library at some point ?

**Comment by NorthbySouth** [comment]
Yes. I believe there is another Artnet library installed. I will delete it right now and try again!

**Comment by NorthbySouth** [comment]
That fixed it sorry for the silly mistake. Appreciate the help!

**Comment by natcl** [comment]
No problem, glad to help !
